# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='artist_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
