# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170203_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(blank=True, default='', max_length=200)),
                ('song_length', models.IntegerField()),
            ],
        ),
    ]
