# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(blank=True, default='', max_length=200)),
                ('album_length', models.IntegerField()),
            ],
        ),
    ]
